# SPDX-FileCopyrightText: 2019 Peter Lemenkov <lemenkov@gmail.com>
# SPDX-License-Identifier: MIT

"""Known-answer vectors for the Oracle NUMBER decoder (decode_number).

The byte↔value pairs below are authoritative: each was generated by
``SELECT dump(<literal>) FROM dual`` against a live Oracle server, so the bytes
are exactly what Oracle puts on the wire (a NUMBER is base-100 float — see
``seerdb.common.types.decode_number``). The *choice* of values (sign, powers of
ten, precision boundaries, int64/uint64 limits) covers the same ground as
go-ora's number test table; the vectors themselves are Oracle output.

Regenerate with tools/gen_number_vectors.py against any live Oracle.
"""

import unittest
from decimal import Decimal

from seerdb.common.tns import encode_token_decimal
from seerdb.common.types import decode_number

# (expected decoded value, wire bytes as hex). Comment = the SQL literal dumped.
VECTORS = [
    (0, '80'),  # 0
    (1, 'c102'),  # 1
    (-1, '3e6466'),  # -1
    (10, 'c10b'),  # 10
    (100, 'c202'),  # 100
    (1000, 'c20b'),  # 1000
    (10000000, 'c40b'),  # 10000000
    (123456789, 'c502182e445a'),  # 123456789
    (-123456789, '3a644e38220c66'),  # -123456789
    (Decimal('0.1'), 'c00b'),  # 0.1
    (Decimal('0.001'), 'bf0b'),  # 0.001
    (Decimal('-0.001'), '405b66'),  # -0.001
    (Decimal('0.5'), 'c033'),  # 0.5
    (Decimal('0.25'), 'c01a'),  # 0.25
    (Decimal('0.125'), 'c00d33'),  # 0.125
    (Decimal('1.5'), 'c10233'),  # 1.5
    (Decimal('100.5'), 'c2020133'),  # 100.5
    (Decimal('1.234'), 'c1021829'),  # 1.234
    (Decimal('-1.234'), '3e644e3d66'),  # -1.234
    (Decimal('999999999999.9999'), 'c66464646464646464'),  # 999999999999.9999
    (Decimal('9999999999999.999'), 'c70a646464646464645b'),  # 9999999999999.999
    (Decimal('99999999999999.99'), 'c76464646464646464'),  # 99999999999999.99
    (9999999999999999, 'c86464646464646464'),  # 9999999999999999
    (9223372036854775807, 'ca0a1722490445374e3b08'),  # max int64
    (-9223372036854775808, '355c4f441d62212f182b5d66'),  # min int64
    (18446744073709551615, 'ca132d442d08260a381110'),  # max uint64
    (10**30, 'd002'),  # 1E30
    (
        Decimal('3.1415926535897932384626433832795'),
        'c1040f105d42245a5021272f1b2c27215033',
    ),  # pi to 31 digits (near NUMBER's 38-digit precision)
]


class TestNumberDecodeVectors(unittest.TestCase):
    def test_known_answer_vectors(self):
        for Expected, Hex in VECTORS:
            with self.subTest(value=str(Expected)):
                Got = decode_number(bytes.fromhex(Hex))
                self.assertEqual(Got, Expected)
                # Integers must decode as int, non-integers as Decimal — the
                # value equality above treats 10 == Decimal('10') as equal.
                self.assertIs(type(Got), type(Expected))

    def test_empty_is_null(self):
        # A zero-length NUMBER on the wire is SQL NULL.
        self.assertIsNone(decode_number(b''))


class TestNumberEncodeVectors(unittest.TestCase):
    def test_encode_matches_oracle_canonical_bytes(self):
        # The other direction: encode_token_decimal must produce the exact
        # base-100 bytes Oracle itself emits (the same vectors, DUMP-derived).
        for Expected, Hex in VECTORS:
            with self.subTest(value=str(Expected)):
                self.assertEqual(
                    encode_token_decimal(Decimal(Expected)), bytes.fromhex(Hex)
                )


if __name__ == '__main__':
    unittest.main()
